spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: yxy010918

    druid:
      #开启SQL监控和防火墙
      filters: stat,wall,slf4j    # 底层开启功能，stat（sql监控），wall（防火墙）
      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
        #监控web应用
      web-stat-filter: # 监控web
        enabled: true
        url-pattern: /*
        exclusions:

      aop-patterns: com.yxy.*   #监控SpringBean
      filter:
        stat: # 对上面filters里面的stat的详细配置
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          config:
            select-allow: true
            table-check: true
            #是否允许updateSQL语句操作
            update-allow: true

